import type { Metadata } from "next";
import { Geist, Geist_Mono, Raleway, Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Header from "@/components/ui/header";
import { createClient } from "@/lib/server";
import { cookies, headers } from "next/headers";
import { getCartItems } from "@/managers/getCartItems";
import { getOrCreateCart } from "@/lib/cart";
import { CartProvider } from "@/context/cartContext";

const raleway = Raleway({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const interMono = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = await createClient();
  const cookieStore = await cookies();
  const headersList = await headers();

  const [categoriesRes, cartItemsRes] = await Promise.all([
    supabase.from("categories").select("*"),

    getCartItems(),
  ]);

  const cartId = cookieStore.get("cart_id")?.value ?? "";
  if (cartId) {
    await getOrCreateCart(cartId);
  } 
  const currentPath = headersList.get("referer")
    ? new URL(headersList.get("referer")!).pathname
    : "/";

  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        geistSans.variable,
        geistMono.variable,
        "font-sans",
        raleway.variable,
        interMono.variable,
      )}
    >
      <body className="min-h-full flex justify-center">
        <CartProvider cartId={cartId}>
        <div className="w-full max-w-[1920px]  flex shadow-2xl flex-col">
          <Header
            categories={categoriesRes.data || []}
            cartItems={cartItemsRes}
            currentPath={currentPath}
            cartId={cartId}
          />
          <main>{children}</main>
        </div>
        </CartProvider>
      </body>
    </html>
  );
}
